<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>DataDriven_Login_Test</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>2b47c105-457e-4dca-ac75-212fa390afee</testSuiteGuid>
   <testCaseLink>
      <guid>1a1ad5f7-d123-4c63-a94d-bc7b837392f2</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Data Driven Tests/Login</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>4f4e6ce4-cb31-47d9-b42b-bb4a6c314656</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/CURA_Healthcare/LoginData</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>4f4e6ce4-cb31-47d9-b42b-bb4a6c314656</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Username</value>
         <variableId>83535a36-207f-4a79-baf1-0f127b676d1a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>4f4e6ce4-cb31-47d9-b42b-bb4a6c314656</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Password</value>
         <variableId>0678f519-2dde-403d-aa4a-5e019b5ef52a</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
